FROM ubuntu:latest

FROM gradle:8.8-jdk17 AS builder

WORKDIR /opt/user
COPY user-service ./
RUN gradle clean build --no-daemon


FROM openjdk:17-jdk-slim
EXPOSE 8082
COPY --from=builder /opt/user/build/libs/user-service.jar /opt/user/build/libs/user-service.jar
CMD ["java", "-jar", "/opt/user/build/libs/user-service.jar"]