FROM ubuntu:latest

FROM gradle:8.8-jdk17 AS builder

WORKDIR /opt/project
COPY chatlink-backend ./
RUN gradle clean build --no-daemon


FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY --from=builder /opt/project/build/libs/chatlink-backend-0.0.1-SNAPSHOT.jar /opt/project/build/libs/chatlink-backend-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/opt/project/build/libs/chatlink-backend-0.0.1-SNAPSHOT.jar"]